# https://taskfile.dev

version: '3'

dotenv: ['.env']

vars:
  ChartPath: ./charts/arma3

tasks:
  default:
    cmds:
    - task: helm
    silent: true

  build:
    desc: Build docker image
    cmds:
    - docker build -t ghcr.io/brittonhayes/arma3server .

  helm:
    desc: Execute helm template and documentation generation
    cmds:
    - helm template arma3 {{ .ChartPath }} --values values.yaml | kubeconform -summary
    - helm-docs -c {{ .ChartPath }}

  helm:install:
    desc: Install helm chart to cluster
    cmds:
    - helm -n arma3 install arma3 {{ .ChartPath }} --values values.yaml

  helm:upgrade:
    desc: Release helm chart to cluster
    cmds:
    - helm upgrade -n arma3 --values values.yaml --install arma3 {{ .ChartPath }}

  helm:uninstall:
    desc: Uninstall helm chart from cluster
    cmds:
    - helm -n arma3 uninstall arma3