# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
    - task: helm
    silent: true

  helm:
    desc: Execute helm template and documentation generation
    cmds:
    - helm template arma3 ./charts | kubeconform -summary
    - helm-docs -c ./charts
