{{- if .Values.headlessclient.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arma3.fullname" . }}-headlessclient
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arma3.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{ .Values.headlessclient.name }}.Arma3Profile: |-
    battleyeLicense=1;
    version=1;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arma3.fullname" . }}-headlessclient-env
  labels:
    {{- include "arma3.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.config.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}